const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  soothingColors : [
    // "#FFF9DE",
    // "#FFD1DA",
    // "#FFDDCC",
    // "#9BE8D8",
    // "#FFCCCC",
    // "#FFEEF4",
    // "#DFCCFB",
    // "#AEE2FF",
    // "#FFD3B0",
    // "#DAF5FF",
    // "#E3DFFD",
    // "#FFF8E1",
    // "#FFE5F1",
    // "#FBFACD",
    // "#CDF0EA",
    // "#FFE1A8",
    // "#CCF3EE",
    // "#D6E5FA",
    // "#FFF5AB",
    // "#E4F1FF"
    "#FEFF86",  
    "#97FEED",
    "#FFD9C0",
    "#DDFFBB",
    "#FFF2CC",
    "#FFD966",
    "#E5D1FA",
    "#FFD4D4",
    "#DFD3C3",
    "#E4F1FF",
    "#FBFACD",
    "#CAEDFF",
    "#D0BFFF",
    "#F3FDE8",
    "#FFE5E5",
  ]
};